// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: prototype/chain.service.response.proto

package prototype

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlockValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num          uint64     `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	Hash         string     `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Parent       string     `protobuf:"bytes,3,opt,name=parent,proto3" json:"parent,omitempty"`
	Timestamp    uint64     `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Proposer     string     `protobuf:"bytes,5,opt,name=proposer,proto3" json:"proposer,omitempty"`
	Approvers    []string   `protobuf:"bytes,6,rep,name=approvers,proto3" json:"approvers,omitempty"`
	Slashers     []string   `protobuf:"bytes,7,rep,name=slashers,proto3" json:"slashers,omitempty"`
	Transactions []*TxValue `protobuf:"bytes,8,rep,name=transactions,proto3" json:"transactions,omitempty"`
}

func (x *BlockValue) Reset() {
	*x = BlockValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prototype_chain_service_response_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockValue) ProtoMessage() {}

func (x *BlockValue) ProtoReflect() protoreflect.Message {
	mi := &file_prototype_chain_service_response_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockValue.ProtoReflect.Descriptor instead.
func (*BlockValue) Descriptor() ([]byte, []int) {
	return file_prototype_chain_service_response_proto_rawDescGZIP(), []int{0}
}

func (x *BlockValue) GetNum() uint64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *BlockValue) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *BlockValue) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *BlockValue) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BlockValue) GetProposer() string {
	if x != nil {
		return x.Proposer
	}
	return ""
}

func (x *BlockValue) GetApprovers() []string {
	if x != nil {
		return x.Approvers
	}
	return nil
}

func (x *BlockValue) GetSlashers() []string {
	if x != nil {
		return x.Slashers
	}
	return nil
}

func (x *BlockValue) GetTransactions() []*TxValue {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type TxValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num       uint64           `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	Type      uint32           `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Timestamp uint64           `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Hash      string           `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	Fee       uint64           `protobuf:"varint,5,opt,name=fee,proto3" json:"fee,omitempty"`
	Data      []byte           `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	Inputs    []*TxInputValue  `protobuf:"bytes,7,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs   []*TxOutputValue `protobuf:"bytes,8,rep,name=outputs,proto3" json:"outputs,omitempty"`
}

func (x *TxValue) Reset() {
	*x = TxValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prototype_chain_service_response_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxValue) ProtoMessage() {}

func (x *TxValue) ProtoReflect() protoreflect.Message {
	mi := &file_prototype_chain_service_response_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxValue.ProtoReflect.Descriptor instead.
func (*TxValue) Descriptor() ([]byte, []int) {
	return file_prototype_chain_service_response_proto_rawDescGZIP(), []int{1}
}

func (x *TxValue) GetNum() uint64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *TxValue) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *TxValue) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TxValue) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *TxValue) GetFee() uint64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *TxValue) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TxValue) GetInputs() []*TxInputValue {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *TxValue) GetOutputs() []*TxOutputValue {
	if x != nil {
		return x.Outputs
	}
	return nil
}

type TxInputValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash    string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Index   uint32 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Address string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Amount  uint64 `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *TxInputValue) Reset() {
	*x = TxInputValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prototype_chain_service_response_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxInputValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxInputValue) ProtoMessage() {}

func (x *TxInputValue) ProtoReflect() protoreflect.Message {
	mi := &file_prototype_chain_service_response_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxInputValue.ProtoReflect.Descriptor instead.
func (*TxInputValue) Descriptor() ([]byte, []int) {
	return file_prototype_chain_service_response_proto_rawDescGZIP(), []int{2}
}

func (x *TxInputValue) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *TxInputValue) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *TxInputValue) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *TxInputValue) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type TxOutputValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Amount  uint64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Node    string `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`
}

func (x *TxOutputValue) Reset() {
	*x = TxOutputValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prototype_chain_service_response_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxOutputValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxOutputValue) ProtoMessage() {}

func (x *TxOutputValue) ProtoReflect() protoreflect.Message {
	mi := &file_prototype_chain_service_response_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxOutputValue.ProtoReflect.Descriptor instead.
func (*TxOutputValue) Descriptor() ([]byte, []int) {
	return file_prototype_chain_service_response_proto_rawDescGZIP(), []int{3}
}

func (x *TxOutputValue) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *TxOutputValue) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TxOutputValue) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

var File_prototype_chain_service_response_proto protoreflect.FileDescriptor

var file_prototype_chain_service_response_proto_rawDesc = []byte{
	0x0a, 0x26, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19, 0x72, 0x64, 0x6f, 0x2e, 0x63, 0x68,
	0x61, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x86, 0x02, 0x0a, 0x0a, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x03, 0x6e, 0x75, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x65,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x70,
	0x70, 0x72, 0x6f, 0x76, 0x65, 0x72, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x61,
	0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x72, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x6c, 0x61, 0x73,
	0x68, 0x65, 0x72, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x73, 0x6c, 0x61, 0x73,
	0x68, 0x65, 0x72, 0x73, 0x12, 0x46, 0x0a, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x72, 0x64, 0x6f,
	0x2e, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x54, 0x78, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0c,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x8c, 0x02, 0x0a,
	0x07, 0x54, 0x78, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04,
	0x68, 0x61, 0x73, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68,
	0x12, 0x10, 0x0a, 0x03, 0x66, 0x65, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x66,
	0x65, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x3f, 0x0a, 0x06, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x73,
	0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x72, 0x64, 0x6f, 0x2e, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x54, 0x78, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52,
	0x06, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x12, 0x42, 0x0a, 0x07, 0x6f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x72, 0x64, 0x6f, 0x2e, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x54, 0x78, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x52, 0x07, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x22, 0x6a, 0x0a, 0x0c, 0x54,
	0x78, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68,
	0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12,
	0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x55, 0x0a, 0x0d, 0x54, 0x78, 0x4f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f,
	0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x42, 0x17,
	0x5a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x2e, 0x3b, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x74, 0x79, 0x70, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_prototype_chain_service_response_proto_rawDescOnce sync.Once
	file_prototype_chain_service_response_proto_rawDescData = file_prototype_chain_service_response_proto_rawDesc
)

func file_prototype_chain_service_response_proto_rawDescGZIP() []byte {
	file_prototype_chain_service_response_proto_rawDescOnce.Do(func() {
		file_prototype_chain_service_response_proto_rawDescData = protoimpl.X.CompressGZIP(file_prototype_chain_service_response_proto_rawDescData)
	})
	return file_prototype_chain_service_response_proto_rawDescData
}

var file_prototype_chain_service_response_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_prototype_chain_service_response_proto_goTypes = []interface{}{
	(*BlockValue)(nil),    // 0: rdo.chainservice.response.BlockValue
	(*TxValue)(nil),       // 1: rdo.chainservice.response.TxValue
	(*TxInputValue)(nil),  // 2: rdo.chainservice.response.TxInputValue
	(*TxOutputValue)(nil), // 3: rdo.chainservice.response.TxOutputValue
}
var file_prototype_chain_service_response_proto_depIdxs = []int32{
	1, // 0: rdo.chainservice.response.BlockValue.transactions:type_name -> rdo.chainservice.response.TxValue
	2, // 1: rdo.chainservice.response.TxValue.inputs:type_name -> rdo.chainservice.response.TxInputValue
	3, // 2: rdo.chainservice.response.TxValue.outputs:type_name -> rdo.chainservice.response.TxOutputValue
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_prototype_chain_service_response_proto_init() }
func file_prototype_chain_service_response_proto_init() {
	if File_prototype_chain_service_response_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_prototype_chain_service_response_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prototype_chain_service_response_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prototype_chain_service_response_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxInputValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prototype_chain_service_response_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxOutputValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_prototype_chain_service_response_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_prototype_chain_service_response_proto_goTypes,
		DependencyIndexes: file_prototype_chain_service_response_proto_depIdxs,
		MessageInfos:      file_prototype_chain_service_response_proto_msgTypes,
	}.Build()
	File_prototype_chain_service_response_proto = out.File
	file_prototype_chain_service_response_proto_rawDesc = nil
	file_prototype_chain_service_response_proto_goTypes = nil
	file_prototype_chain_service_response_proto_depIdxs = nil
}
